default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: douglas
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: rpg_development


test:
  <<: *default
  database: rpg_test

production:
  <<: *default
  username: douglas
  password:
  host: 'ec2-54-225-101-199.compute-1.amazonaws.com'
  database: df7k6r2rdju8l2
  username: hunjzngljrmidv
  password: oBrRGvSTv9ZO1mKU6j7vk9kxT_
